type: object
properties:
  function:
    type: string
    description: Name of the API function to execute.
    const: GetAdvancedGameSettings
    default: GetAdvancedGameSettings
    example: GetAdvancedGameSettings
required:
- function
