openapi: 3.1.0
info:
  title: Satisfactory Game Server HTTPS API specification
  description: Satisfactory Game Server HTTPS API specification
  version: 0.0.0-replace
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
- url: 'https://localhost:7777'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # HealthCheck
  '/api/v1/?function=HealthCheck':
    $ref: functions\healthCheck\healthCheck.yml

  # VerifyAuthenticationToken
  '/api/v1/?function=VerifyAuthenticationToken':
    $ref: functions\verifyAuthenticationToken\verifyAuthenticationToken.yml

  # PasswordlessLogin
  '/api/v1/?function=PasswordlessLogin':
    $ref: functions\passwordlessLogin\PasswordlessLogin.yml

  # PasswordLogin
  '/api/v1/?function=PasswordLogin':
    $ref: functions\passwordLogin\passwordLogin.yml

  # QueryServerState
  '/api/v1/?function=QueryServerState':
    $ref: functions\queryServerState\queryServerState.yml

  # GetServerOptions
  '/api/v1/?function=GetServerOptions':
    $ref: functions\getServerOptions\getServerOptions.yml

  # GetAdvancedGameSettings
  '/api/v1/?function=GetAdvancedGameSettings':
    $ref: functions\getAdvancedGameSettings\getAdvancedGameSettings.yml

  # ApplyAdvancedGameSettings
  '/api/v1/?function=ApplyAdvancedGameSettings':
    $ref: functions\applyAdvancedGameSettings\applyAdvancedGameSettings.yml

  # ClaimServer
  '/api/v1/?function=ClaimServer':
    $ref: functions\claimServer\claimServer.yml

  # RenameServer
  '/api/v1/?function=RenameServer':
    $ref: functions\renameServer\renameServer.yml

  # SetClientPassword
  '/api/v1/?function=SetClientPassword':
    $ref: functions\setClientPassword\setClientPassword.yml

  # SetAdminPassword
  '/api/v1/?function=SetAdminPassword':
    $ref: functions\setAdminPassword\setAdminPassword.yml
