openapi: 3.1.0
info:
  title: Satisfactory Game Server HTTPS API specification
  description: Satisfactory Game Server HTTPS API specification
  version: 0.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
- url: 'https://localhost:7777'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
- name: Setup
  description: Authorization
- name: Authorization
  description: Authorization
- name: Server
  description: Server Status
- name: Game
  description: Game Settings
- name: Saves
  description: Saves
- name: Sessions
  description: Sessions
paths:

  # --- Setup

  # ClaimServer
  '/api/v1/?function=ClaimServer':
    $ref: functions/claimServer/claimServer.yml

  # CreateNewGame
  '/api/v1/?function=CreateNewGame':
    $ref: functions/createNewGame/createNewGame.yml

  # --- Authorization

  # PasswordlessLogin
  '/api/v1/?function=PasswordlessLogin':
    $ref: functions/passwordlessLogin/passwordlessLogin.yml

  # PasswordLogin
  '/api/v1/?function=PasswordLogin':
    $ref: functions/passwordLogin/passwordLogin.yml

  # SetClientPassword
  '/api/v1/?function=SetClientPassword':
    $ref: functions/setClientPassword/setClientPassword.yml

  # SetAdminPassword
  '/api/v1/?function=SetAdminPassword':
    $ref: functions/setAdminPassword/setAdminPassword.yml

  # VerifyAuthenticationToken
  '/api/v1/?function=VerifyAuthenticationToken':
    $ref: functions/verifyAuthenticationToken/verifyAuthenticationToken.yml

  # --- Sessions
  # - Placed here to keep a specific ordering in our generated documentation

  # EnumerateSessions
  '/api/v1/?function=EnumerateSessions':
    $ref: functions/enumerateSessions/enumerateSessions.yml

  # --- Server

  # HealthCheck
  '/api/v1/?function=HealthCheck':
    $ref: functions/healthCheck/healthCheck.yml

  # GetServerOptions
  '/api/v1/?function=GetServerOptions':
    $ref: functions/getServerOptions/getServerOptions.yml

  # ApplyServerOptions
  '/api/v1/?function=ApplyServerOptions':
    $ref: functions/applyServerOptions/applyServerOptions.yml

  # SetAutoLoadSessionName
  '/api/v1/?function=SetAutoLoadSessionName':
    $ref: functions/setAutoLoadSessionName/setAutoLoadSessionName.yml

  # QueryServerState
  '/api/v1/?function=QueryServerState':
    $ref: functions/queryServerState/queryServerState.yml

  # RenameServer
  '/api/v1/?function=RenameServer':
    $ref: functions/renameServer/renameServer.yml

  # RunCommand
  '/api/v1/?function=RunCommand':
    $ref: functions/runCommand/runCommand.yml

  # Shutdown
  '/api/v1/?function=Shutdown':
    $ref: functions/shutdown/shutdown.yml

  # --- Sessions
  # - Placed here to keep a specific ordering in our generated documentation

  # DeleteSaveSession
  '/api/v1/?function=DeleteSaveSession':
    $ref: functions/deleteSaveSession/deleteSaveSession.yml

  # --- Game

  # GetAdvancedGameSettings
  '/api/v1/?function=GetAdvancedGameSettings':
    $ref: functions/getAdvancedGameSettings/getAdvancedGameSettings.yml

  # ApplyAdvancedGameSettings
  '/api/v1/?function=ApplyAdvancedGameSettings':
    $ref: functions/applyAdvancedGameSettings/applyAdvancedGameSettings.yml

  # --- Saves

  # SaveGame
  '/api/v1/?function=SaveGame':
    $ref: functions/saveGame/saveGame.yml

  # DownloadSaveGame
  '/api/v1/?function=DownloadSaveGame':
    $ref: functions/downloadSaveGame/downloadSaveGame.yml

  # UploadSaveGame
  '/api/v1/?function=UploadSaveGame':
    $ref: functions/uploadSaveGame/uploadSaveGame.yml

  # LoadGame
  '/api/v1/?function=LoadGame':
    $ref: functions/loadGame/loadGame.yml

  # DeleteSaveFile
  '/api/v1/?function=DeleteSaveFile':
    $ref: functions/deleteSaveFile/deleteSaveFile.yml
