type: object
properties:
  appliedAdvancedGameSettings:
    type: object
    description: Values of Advanced Game Settings. Key is the name of the setting, and value is its stringified value
    additionalProperties:
      type: string
    example:
      FG.GameRules.NoPower: "False"
      FG.GameRules.StartingTier: "0"
      FG.GameRules.DisableArachnidCreatures: "False"
      FG.GameRules.NoUnlockCost: "False"
      FG.GameRules.SetGamePhase: "0"
      FG.GameRules.UnlockAllResearchSchematics: "False"
      FG.GameRules.UnlockInstantAltRecipes: "False"
      FG.GameRules.UnlockAllResourceSinkSchematics: "False"
      FG.PlayerRules.NoBuildCost: "False"
      FG.PlayerRules.GodMode: "False"
      FG.PlayerRules.FlightMode: "False"
required:
- appliedAdvancedGameSettings
