# Simple workflow for deploying static content to GitHub Pages
name: Deploy - Pages

on:
  push:
    branches: gh-pages
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup - Pages
        uses: actions/configure-pages@v5

      - name: Upload - Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy - Pages
        id: deployment
        uses: actions/deploy-pages@v4
